CREATE TABLE event (
  id NUMBER(38, 0) GENERATED BY DEFAULT AS IDENTITY,
   name VARCHAR2(255),
   location VARCHAR2(255),
   description VARCHAR2(255),
   capacity NUMBER(38, 0) NOT NULL,
   event_date TIMESTAMP,
   flyer_path VARCHAR2(255),
   CONSTRAINT pk_event PRIMARY KEY (id)
);

CREATE TABLE artist (
  id NUMBER(38, 0) GENERATED BY DEFAULT AS IDENTITY,
   first_name VARCHAR2(255),
   last_name VARCHAR2(255),
   nickname VARCHAR2(255),
   email VARCHAR2(255),
   phone_number VARCHAR2(255),
   picture_path VARCHAR2(255),
   CONSTRAINT pk_artist PRIMARY KEY (id)
);


CREATE TABLE artist_event (
  artist_id NUMBER(38, 0) NOT NULL,
   event_id NUMBER(38, 0) NOT NULL,
   CONSTRAINT pk_artist_event PRIMARY KEY (artist_id, event_id)
);

ALTER TABLE artist_event ADD CONSTRAINT fk_arteve_on_artist FOREIGN KEY (artist_id) REFERENCES artist (id);

ALTER TABLE artist_event ADD CONSTRAINT fk_arteve_on_event FOREIGN KEY (event_id) REFERENCES event (id);


insert into artist (first_name, last_name, nickname, email, phone_number) values
('Alberto', 'Rinaldi','Alberto Rinaldi','alberto.rinaldi@mail.com', '3401234567');

insert into artist (first_name, last_name, nickname, email, phone_number) values
('Sam', 'Egiziano','Lethal Frame','sam.egiziano@mail.com', '3498765432');

insert into artist (first_name, last_name, nickname, email, phone_number) values
('Matteo', 'Fornasa','Formhat','forno@mail.com', '340121297');




insert into event(name, location, description, capacity, event_date) values
('VOL 1', 'Nido, Ronca', 'FIRST HERTZ EVENT', 250, TO_DATE('2010-09-09T18:00:00' ,'YYYY-MM-DD"T"HH24:MI:SS"'));


CREATE SEQUENCE ARTIST_SEQ START WITH 1 INCREMENT BY 1;

CREATE SEQUENCE EVENT_SEQ START WITH 1 INCREMENT BY 1;
